### ISSUE TITLE
QC summary

### ISSUE THREAD

**Issue by coaxlab0** [CoAxLab/niphlem#3]
Summary plots showing:

- Average QRS waveform (if using EKG data).
- Average pulse-ox peak (separated for high and low frequencies)
- Average respiration belt wave form
- Inter-peak intervals for cardiac and respiration measures separately
- Signal-to-noise or other quality metrics.

Preferably as .html output file.

**Comment by asentis** [comment]
Also look into typical quality metrics used for ECG, respiratory data (e.g. histograms, signal-to-noise)

**Comment by jrasero** [comment]
For now we only have this implemented for the ECG. We need to create the same QC  functions for the other data (respiration & pulse-ox)

**Comment by jrasero** [comment]
Closing this. The remaining work to do (QC for respiration and pulse-ox) has been added to the Projects tab
